[env:esp32doit-devkit-v1]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32doit-devkit-v1
framework = arduino

monitor_speed = 115200
board_build.filesystem = littlefs

board_upload.com_port = /dev/ttyACM0
board_upload.wait_for_upload_port = yes
board_upload.use_1200bps_touch = yes


build_flags =
    -D DEBUG_LEVEL=2
    ; DEBUG_LEVEL values:
    ; 1 = errors only
    ; 2 = warnings + startup flow (current default)
    ; 3 = detailed debug
    ; 4 = verbose tracing
 
lib_deps =
    lib/vendor/rc-switch
    lib/vendor/irremote
    ArduinoJson @ ^6.18
    https://github.com/ESP32Async/AsyncTCP.git#v3.4.10
    https://github.com/ESP32Async/ESPAsyncWebServer.git#v3.11.2
    adafruit/Adafruit GFX Library@^1.11.5
    adafruit/Adafruit NeoPixel@^1.9.0


