; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
build_flags = 
	   -D DEBUG_LEVEL=3

lib_deps = 
	sui77/rc-switch
	z3t0/IRremote @ ^4.4.1
monitor_speed = 115200
;upload_port = COM6
;upload_speed = 921600
board_upload.wait_for_upload_port = yes
board_upload.use_1200bps_touch = yes
